### ISSUE TITLE
Importing KeePass XML file fails

### ISSUE THREAD

**Issue by nutt318** [nilsteampassnet/teampass_doc#2]
Hello,

I'm trying to import a KeePass xml file into TeamPass and not having any luck. I get the error 'Can't read the file, must be a valid KeePass file' I've also remove the master password from the KeePass database and exported the xml but still the same results. I'm not seeing anything in the logs and cannot figure out what is wrong with the import feature.

Any suggestions?
Thanks

**Comment by nilsteampassnet** [comment]
This is a bug recently identified that had been solved in 2.1.27.3.

Take a look at the release note of this version and identify the ticket number that deals about this issue. Then open the ticket and perform the changes. 

Or you upgrade to latest release of teampass.

**Comment by nutt318** [comment]
Thank you, found the issue, #1737
